export const EXAMPLE_PATH = 'blog-starter'
export const CMS_NAME = 'Markdown'
export const HOME_OG_IMAGE_URL =
  'https://og-image.vercel.app/Next.js%20Blog%20Starter%20Example.png?theme=light&md=1&fontSize=100px&images=https%3A%2F%2Fassets.vercel.com%2Fimage%2Fupload%2Ffront%2Fassets%2Fdesign%2Fnextjs-black-logo.svg'
export const BLOG_NAME = 'TopicTrove.com'
export const KEYWORDS = 'Blog, next.js'
export const DESCRIPTION = 'Dive into the treasure trove of diverse and intriguing topics. Topic Trove is your source for thought-provoking articles, fascinating facts, and random musings that span a wide spectrum of subjects. Explore the unexpected gems of knowledge here.'
export const AUTHOR = 'Uzo'
export const LANG = 'en-CA'
export const GITHUB_REPO = 'https://github.com/Chibudomcode4114'
